### ISSUE TITLE
Question on Sampling Strategy

### ISSUE THREAD

**Issue by anuveshkumar** [GhiXu/Geo-Neus#2]
Hi, 
I have a doubt related to the sampling strategy used in Photometric and RGB Loss

![image](https://user-images.githubusercontent.com/15230230/180148937-59d8c266-781b-49c6-ac35-3761c00f7973.png)

Photometric losses require patches to calculate the NCC. 

Are you obtaining the patches by rendering only patches... and using the rendered values for calculating both NCC and RGB loss ?

OR

Are you rendering random pixels (which you use for RGB loss)
and then take patches only around those pixels which intersect the object, and the RGB values of the patch comes from the reference image (and not by rendering the remaining pixels) ?

**Comment by GhiXu** [comment]
Hi, @anuveshkumar, we use the later strategy to compute RGB loss and NCC scores.

**Comment by anuveshkumar** [comment]
Thank You. That answers my question.
